# Generated by Django 5.0 on 2023-12-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_rate', models.PositiveIntegerField(default=60)),
                ('max_books', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
