# Generated by Django 5.0 on 2023-12-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('recommendations', '0003_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.book'),
        ),
    ]
